### ISSUE TITLE
Code edit please

### ISSUE THREAD

**Issue by djangman** [illustrastock/EDD-Checkify#1]
Hi Toni, could you please remove my name and email from this good-writer-checkify.php file.  I'm the original author of this plugin, and I'm just trying to prevent this from coming up on a google search.

Also please remove "Contact: The contact page for my plugins is: ContactForm" from your readme.md, because I am having too many people go to my contact form on my web site. 
Thank you
Steve Bailey

**Comment by colomet** [comment]
ok.
